---
- name: create mars folder
  file:
    path: "{{ ansible_env['HOME'] }}/mars"
    state: directory
    mode: 0755
  tags:
    - eclipse
    - sudotask

- name: download mars
  get_url:
    url: http://eclipse.bluemix.net/packages/mars.1/data/eclipse-java-mars-1-linux-gtk-x86_64.tar.gz
    dest: "{{ ansible_env['HOME'] }}/mars/mars.tar.gz"
    mode: 0400
  tags:
    - eclipse
    - sudotask

- name: unzip mars
  unarchive:
    src: "{{ ansible_env['HOME'] }}/mars/mars.tar.gz"
    dest: "{{ ansible_env['HOME'] }}/mars"
    mode: 0755
  tags:
    - eclipse
    - sudotask

- name: put root eclipse shortcut
  template:
    src: eclipse.sh.j2 
    dest: /root/.bashloader.d/eclipse.sh
    mode: 0644
  sudo: yes
  tags:
    - eclipse
    - bashrc
    - sudotask

