---
- name: create neon folder
  file:
    path: "{{ ansible_env['HOME'] }}/neon"
    state: directory
    mode: 0755
  tags:
    - eclipse

- name: download neon
  get_url:
    url: http://ftp-stud.fht-esslingen.de/pub/Mirrors/eclipse/technology/epp/downloads/release/neon/1/eclipse-java-neon-1-linux-gtk-x86_64.tar.gz
    dest: "{{ ansible_env['HOME'] }}/neon/neon.tar"
    mode: 0755
  tags:
    - eclipse

- name: unzip neon
  unarchive:
    src: "{{ ansible_env['HOME'] }}/neon/neon.tar"
    dest: "{{ ansible_env['HOME'] }}/neon"
    mode: 0755
  tags:
    - eclipse

- name: put root eclipse shortcut
  template:
    src: eclipse.sh.j2 
    dest: /root/.bashloader.d/eclipse.sh
    mode: 0644
  become: true
  tags:
    - eclipse
    - bashrc

