---
- name: create sonarqube folder
  file:
    path: "{{ ansible_env['HOME'] }}/sonarqube"
    state: directory
    mode: 0755

- name: download sonarqube
  get_url:
    url: http://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-dist/2.4/sonar-runner-dist-2.4.zip
    dest: "{{ ansible_env['HOME'] }}/sonarqube/sonarqube.zip"
    mode: 0400

- name: unzip sonarqube
  unarchive:
    src: "{{ ansible_env['HOME'] }}/sonarqube/sonarqube.zip"
    dest: "{{ ansible_env['HOME'] }}/sonarqube"
    mode: 0755

- name: put shortcut in bash
  template:
    src: sonarqube.sh.j2 
    dest: "{{ ansible_env['HOME'] }}/.bashloader.d/sonarqube.sh"
    mode: 0644

