---
- name: install mysql-server
  sudo: yes
  yum:
    name={{ item }}
  with_items:
    - mysql-server
    - MySQL-python

- name: start mysql-server
  sudo: yes
  command: "/sbin/service mysqld start"
  changed_when: false

- name: create sonar database
  mysql_db:
    name: sonar
    encoding: utf8
    login_user: root
    login_password: ""
    state: present

- name: create sonar user
  mysql_user:
    name: "sonar"
    password: "sonar" 
    priv: sonar.*:ALL
    login_user: root
    login_password: ""
    state: present

