---
- name: download sonarqube
  get_url:
    url: "https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-4.5.6.zip"
    dest: "{{ ansible_env['HOME'] }}/sonarqube/sonarqube.zip"
    mode: 0400

- name: unzip sonarqube
  unarchive:
    src: "{{ ansible_env['HOME'] }}/sonarqube/sonarqube.zip"
    dest: "{{ ansible_env['HOME'] }}/sonarqube"
    mode: 0755
  changed_when: false

- name: create sonar folder in opt
  sudo: yes
  file:
    path: "/opt/sonar"
    state: directory
    mode: 0755

- name: precheck if folder already exists
  stat: path=/opt/sonar/sonarqube-4.5.6
  register: sonarqubeStat

- name: move sonarqube to opt 
  sudo: yes
  command: mv "{{ ansible_env['HOME'] }}/sonarqube/sonarqube-4.5.6" "/opt/sonar"
  when: sonarqubeStat.stat.isdir is not defined
  
# better with replace?
- name: setup sonar cube conf sonar.properties
  sudo: yes
  lineinfile:
    dest: /opt/sonar/sonarqube-4.5.6/conf/sonar.properties
    state: present
    backup: yes
    regexp: '^#{{ item }}$'
    line: "{{ item }}"
  with_items: 
    - "sonar.jdbc.username=sonar"
    - "sonar.jdbc.password=sonar"
    - "sonar.jdbc.url=jdbc:mysql://localhost:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance"
    - "sonar.web.host=127.0.0.1"
    - "sonar.web.context=/sonar"
    - "sonar.web.port=9000"
