---
- name: download sonarqube
  get_url:
    url: "https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-4.5.6.zip"
    dest: "{{ ansible_env['HOME'] }}/sonarqube/sonarqube.zip"
    mode: 0400

- name: unzip sonarqube
  unarchive:
    src: "{{ ansible_env['HOME'] }}/sonarqube/sonarqube.zip"
    dest: "{{ ansible_env['HOME'] }}/sonarqube"
    mode: 0755
  changed_when: false

- name: create sonar folder in opt
  sudo: yes
  file:
    path: "/opt/sonar"
    state: directory
    mode: 0755

- name: precheck if folder already exists
  stat: path=/opt/sonar/sonarqube-4.5.6
  register: sonarqubeStat

- name: move sonarqube to opt 
  sudo: yes
  command: mv "{{ ansible_env['HOME'] }}/sonarqube/sonarqube-4.5.6" "/opt/sonar"
  when: sonarqubeStat.stat.isdir is not defined

- name: set sonar properties
  sudo: yes
  replace:
    dest: /opt/sonar/sonarqube-4.5.6/conf/sonar.properties
    regexp: ^#{{ item.key }}.*
    replace: "{{ item.key }}={{ item.value }}"
  with_items:
    - {key: "sonar.jdbc.username", value: "sonar"}
    - {key: "sonar.jdbc.password", value: "sonar"}
    - {key: "sonar.jdbc.url", value: "jdbc:mysql://localhost:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance"}
    - {key: "sonar.web.context", value: "/sonar"}
    - {key: "sonar.web.port", value: "9000"}
    - {key: "sonar.web.host", value: "127.0.0.1"}
