---
- name: create java8 folder in home
  sudo: yes
  file:
    path: "{{ ansible_env['HOME'] }}/java8"
    state: directory
    mode: 0755

- name: precheck if tar.gz already exists
  sudo: yes
  stat: "path={{ ansible_env['HOME'] }}/java8/{{ RpmName }}.rpm"
  register: java8TarGz
#http://download.oracle.com/otn-pub/java/jdk/8u65-b17/jre-8u65-linux-x64.rpm
#http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jre-8u60-linux-x64.rpm
- name: wget java8 tar.gz
  sudo: yes
  command: "wget --no-cookies --no-check-certificate --header 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie' 'http://download.oracle.com/otn-pub/java/jdk/{{ BuildVersion }}/{{ RpmName }}.rpm' -P {{ ansible_env['HOME'] }}/java8"
  when: java8TarGz.stat.isdir is not defined

- name: install java {{ RpmName }}.rpm
  sudo: yes
  command: "yum localinstall {{ RpmName }}.rpm"

#- name: set latest java version in alternatives
#  sudo: yes
#  command: "alternatives --set java /usr/java/latest/jre/bin/java"
# alternatives --config

- name: put shortcut in bash
  sudo: yes
  template:
    src: java.sh.j2 
    dest: "{{ ansible_env['HOME'] }}/.bashloader.d/java.sh"
    mode: 0644
