---

- hosts: local
  remote_user: root
  roles:
    - common
    - bashrc
    - git
    - IpTables
    - grafics

  vars_prompt:
    - name: "gitHubPassword"
      prompt: "enter git hub password"
      private: yes

