---

- hosts: local
  remote_user: root
  roles:
    - common
    - bashrc
    - git
    - IpTables
    - epages
    - eclipse
    - grafics
    - java
    - sonarqube

  vars_prompt:
    - name: "gitHubPassword"
      prompt: "enter git hub password"
      private: yes

