- name: Creates ~/.bashloader.d directory
  file:
    state: directory
    path: "{{ ansible_env['HOME'] }}/.bashloader.d"
    mode: 0755

- name: Puts the common in the bashloader.d
  copy:
    src: common.sh
    dest: "{{ ansible_env['HOME'] }}/.bashloader.d"
    mode: 0644

- name: add bashload in .bashrc
  lineinfile:
    dest: "{{ ansible_env['HOME'] }}/.bashrc" 
    line: "{{ item }}"
  with_items:
    - "#auto include for multiple .bashrc files"
    - for FILE in $( find "$HOME/.bashloader.d" -type f -print | sort )
    - do
    - \tsource "$FILE"
    - done

- name: load new .bashrc
  shell: "source $HOME/.bashrc"
