- name: load root .bashrc
  sudo: yes
  shell: "cat ~/.bashrc"
  register: bashrcContent
  changed_when: false

- name: set export path for Sublime
  sudo: yes
  shell: "echo 'echo \"set by ansible\"' >> ~/.bashrc"
  when: not bashrcContent.stdout | search("set by ansible") #"