- name: load root .bashrc
  shell: "cat ~/.bashrc"
  register: bashrcContent
  changed_when: false

- name: set export path for Sublime
  shell: "echo 'echo \"### welcome with ansible###\"' >> ~/.bashrc"
  when: not bashrcContent.stdout | search("welcome with ansible") #"
