---
# prepare and set default for user and root
- include: bashrcSetUp.yml UserHome="{{ ansible_env['HOME'] }}"
  tags:
    - bashrc

- include: bashrcSetUp.yml UserHome="/root"
  sudo: yes
  tags:
    - bashrc
