---
- name: set git aliases
  template:
    src=gitAliases.sh.j2
    dest={{ ansible_env['HOME'] }}/.bashloader.d/gitAliases.sh
    mode=0644

- name: set git aliases (root)
  template:
    src=gitAliases.sh.j2
    dest=/root/.bashloader.d/gitAliases.sh
    mode=0644
  become: true

