---

- fail:
    msg: "Please configure the group_vars/all/git.yml first!"
  when: not commiterName or not commiterMail or not gitHubUserName or not gitHubPassword

- name: setup user name
  git_config:
    name: user.name
    scope: global
    value: "{{commiterName}}"

- name: setup user email
  git_config:
    name: user.email
    scope: global
    value: "{{commiterMail}}"


- name: setup push default
  git_config:
    name: push.default
    scope: global
    value: matching


- name: setup core editor
  git_config:
    name: core.editor
    scope: global
    value: vim


# connect git to github
- name: create ssh folder
  file: path=~/.ssh state=directory


- stat: path=~/.ssh/github_ansible_generated
  register: sshkey
  changed_when: false


- name: Creating pub SSH keys - skip if it's already exist
  command: "ssh-keygen -t rsa -b 4096 -f ~/.ssh/github_ansible_generated"
  when: not sshkey.stat.exists


- name: copy public key
  command: "cat ~/.ssh/github_ansible_generated.pub"
  register: publickey
  changed_when: false


- name: add public key to github account
  uri:
    url: https://api.github.com/user/keys
    method: POST
    user: "{{gitHubUserName}}"
    password: "{{gitHubPassword}}"
    body: "{\"title\":\"ansible_generated_{{ansible_user_id}}@{{ansible_hostname}}\",\"key\":\"{{publickey.stdout}}\", \"_hack\": null}" #_hack it is because of a bug in the uri package
    force_basic_auth: yes
    body_format: json
    status_code: 201, 422 #201 - set key, 422 - key is already in use

- include: bashrc.yml
