---

- name: install curl
  become: true
  package:
    name: curl
    state: latest

- name: install vim
  become: true
  package:
    name: vim
    state: latest

- name: install dos2unix
  become: true
  package:
    name: dos2unix
    state: latest

- name: install tree
  become: true
  package:
    name: tree
    state: latest

- name: install jq
  become: true
  package:
    name: jq
    state: latest

- name: install net-tools
  become: true
  package:
    name: net-tools
    state: latest

- name: install sublime ppa
  become: true
  apt_repository:
    repo: "ppa:webupd8team/sublime-text-3"

- name: install sublime
  become: true
  package:
    name: "sublime-text-installer"
    state: latest

- name: install traceroute
  become: true
  package:
    name: "traceroute"
    state: latest

- name: install speedtest-cli
  become: true
  package:
    name: "speedtest-cli"
    state: latest

