---
- name: download install script
  get_url:
    url: "http://www.epages.com/repo/epages/install-epages.sh"
    dest: "/tmp/install-epages.sh"
    mode: 0774
  sudo: yes
  tags:
    - epages
    - epagesinstall

- name: trigger install script
  script: "/tmp/install-epages.sh --singlehost"
  sudo: yes
  tags:
    - epages
    - epagesinstall

- name: remove original cartridge folder
  sudo: yes
  file:
    path="/srv/epages/eproot/Cartridges"
    state=absent
  tags:
    - epages
    - epagesinstall
    - epagesreinstall

- name: clone epages cartridge project
  sudo: yes
  git: repo="git@github.com:ePages-de/Cartridges.git"
    dest="/srv/epages/eproot/Cartridges"
  tags:
    - epages
    - epagesinstall
    - epagesreinstall

- name: set file permissions
  sudo: yes
  shell: "service epages6 perm all"
  tags:
    - epages
    - epagesinstall
    - epagesreinstall

- name: build main makefile
  sudo: yes
  command: "/srv/epages/eproot/Perl/bin/perl Makefile.PL"
  args:
    chdir: "/srv/epages/eproot/Cartridges/DE_EPAGES"
  tags:
    - epages
    - epagesinstall
    - epagesreinstall

- name: make test
  sudo: yes
  command: "make reinstall >> /tmp/instal.log"
  args:
    chdir: "/srv/epages/eproot/Cartridges/DE_EPAGES"
  tags:
    - epages
    - epagesinstall
    - epagesreinstall

